# Generated by Django 3.2 on 2021-05-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_variarion_value_variation_variation_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images',
            new_name='images_1',
        ),
        migrations.AddField(
            model_name='product',
            name='images_2',
            field=models.ImageField(default=0, upload_to='photos/products'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='images_3',
            field=models.ImageField(default=0, upload_to='photos/products'),
            preserve_default=False,
        ),
    ]
