# Generated by Django 3.2 on 2021-05-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='off_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
