# Generated by Django 3.2 on 2021-05-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_refferel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refferel',
            name='update',
            field=models.DateField(auto_now=True),
        ),
    ]
