# Generated by Django 3.2 on 2021-05-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_refferel_update'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refferel',
            old_name='recomended_by',
            new_name='recommended_by',
        ),
    ]
