# Generated by Django 3.2 on 2021-05-18 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_addaddress_order_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddAddress',
        ),
    ]
