# Generated by Django 3.2 on 2021-05-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderproduct_user_cancel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='user_cancel',
            field=models.CharField(default=False, max_length=15, null=True),
        ),
    ]
