# Generated by Django 3.2 on 2021-05-18 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_useraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='order_total',
        ),
    ]
