# Generated by Django 3.2 on 2021-05-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_orderproduct_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
