# Generated by Django 3.2 on 2021-05-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20210520_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
