# Generated by Django 3.2 on 2021-05-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_categoryoffer_productoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoffer',
            name='valid_from',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='valid_to',
            field=models.TextField(),
        ),
    ]
