# Generated by Django 3.2 on 2021-05-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20210525_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='valid_from',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='categoryoffer',
            name='valid_to',
            field=models.CharField(max_length=10),
        ),
    ]
