# Generated by Django 3.2 on 2021-05-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20210525_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=12)),
                ('coupon_price', models.FloatField()),
                ('valid_from', models.CharField(max_length=10)),
                ('valid_to', models.CharField(max_length=10)),
            ],
        ),
    ]
