# Generated by Django 3.2 on 2021-05-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20210528_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupondiscount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
