# Generated by Django 3.2 on 2021-05-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_coupondiscount_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=12)),
                ('coupon_price', models.FloatField(default=10)),
            ],
        ),
    ]
