# Generated by Django 3.2 on 2021-05-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_alter_refcoupon_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='refcoupon',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
